--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: koho
  region: us-east-2
  version: "1.19"

vpc:
  id: __VPC__  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-east-2a:
        id: "__PUBLIC_SUBNET_1__"
        cidr: "192.168.20.0/24" # (optional, must match CIDR used by the given subnet)
      us-east-2b:
        id: "__PUBLIC_SUBNET_2__"
        cidr: "192.168.40.0/24"   # (optional, must match CIDR used by the given subnet)
    private:
      us-east-2a:
        id: "__PRIVATE_SUBNET_1__"
        cidr: "192.168.10.0/24"
      us-east-2b:
        id: "__PRIVATE_SUBNET_2__"
        cidr: "192.168.30.0/24"     

managedNodeGroups:
  - name: core-ng
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 100
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        xRay: true